name: Run Terraform Plan and Validate with Checkov

on:
  workflow_dispatch:

jobs:
  run_checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run Checkov on Terraform plan
        uses: cypiksuresh/shared-workflows/.github/actions/compliance-checkov-tfplan@master
        with:
          tf-policy-repo-token: ${{ secrets.GH_REPO_READ_IAC_TERRAFORM_POLICIES }}
          file-path: 'tfplan.json'           # Path to tfplan.json relative to working-directory
          working-directory: '/home/runner/work/jenkins/jenkins'  # The directory where tfplan.json is located