name: Checkov Github Actions Step

on:
  workflow_dispatch

jobs:
  run_tfplan_and_validate:
    runs-on: ubuntu-latest
    name: A job to call the shared workflow
    steps:
      - uses: actions/checkout@v3
        name: Checkout the latest code

      - name: Set working directory
        id: set_working_dir
        run: echo "WORKING_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Terraform Plan and validate
        run: |
          echo "Working in directory: $WORKING_DIR"
          cd $WORKING_DIR
          terraform init
          terraform plan -out tfplan
          terraform show -json tfplan > ../tfplan.json

      - uses: cypiksuresh/shared-workflows/.github/actions/compliance-checkov-tfplan@master
        with:
          tf-policy-repo-token: ${{ secrets.GH_REPO_READ_IAC_TERRAFORM_POLICIES }}
